import Head from "next/head";

function Home() {
  return (
    <>
      <Head>
        <title>Blogs ▮ enkhee-Osiris</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <p>Hello blogs.</p>
    </>
  );
}

export default Home;
