# Site settings
title: Осирисын хувийн блог
description: > # this means to ignore newlines until "baseurl:"
  Hello World!
baseurl: ""
author:
  name: Энхээ Осирис
  email: enkhee.ag@gmail.com
  youtube: UCJiAzkHY50R8TU6XPgbS8tg
  github: enkhee-Osiris
  facebook: osiris.l33t
  facebook_id: 100003629098903
  instagram: osiris.leet

lang: mn_MN

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Handling Reading
exclude: [Gemfile, Gemfile.lock, README.md]

sass:
  sass_dir: assets/css/_scss
  style: compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Outputting
permalink: /:categories/:year/:month/:day/:title
timezone: Asia/Ulaanbaatar

# assets
BASE_PATH: false
ASSET_PATH: false

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Settings for analytics helper
analytics:
  google:
    tracking_id: "UA-80597159-1"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
