import Head from "next/head";
import { useDarkMode, useIsClient } from "usehooks-ts";

import { styled } from "@/stitches.config";

const Text = styled("p", {
  color: "$gray12",
});

function ThemeToggle() {
  const isClient = useIsClient();
  const { isDarkMode, toggle } = useDarkMode(true);

  if (isClient) {
    return (
      <button type="button" onClick={toggle}>
        {isDarkMode ? "Show me the light" : "Nooo it's too bright"}
      </button>
    );
  }

  return null;
}

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Text as="h1">Hello, from Stitches.</Text>
        <ThemeToggle />
      </>
    </>
  );
}

export default Home;
