name: Deploy GitHub Page

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Lint and Deploy
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OSIRIS_ACCESS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Turbo Cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1.12.0
        with:
          eslint: true
          eslint_extensions: "js,ts,jsx,tsx"
          prettier: true

      - name: Build and deploy
        run: |
          npm run build
          npm run deploy
