name: Deploy GitHub Page

on:
  push:
    branches:
      - master

jobs:
  install:
    name: Install node modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            sites/*/node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit

  lint:
    name: Lint and type check
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            sites/*/node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Lint
        uses: wearerequired/lint-action@v1.12.0
        with:
          eslint: true
          eslint_extensions: "js,ts,jsx,tsx"
          prettier: true

      - name: Type check
        run: npm run type-check

  build:
    name: Build websites
    needs: lint
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache Turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            sites/*/node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Build and deploy
        run: |
          npm run build
          npm run deploy
